server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///java1903
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: consumer_service
  registry:
    address: zookeeper://192.168.140.129:2181
  protocol:
    port: -1
  consumer:
    check: false